/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "query_language.pb-c.h"
void   table_ref__init
                     (TableRef         *message)
{
  static TableRef init_value = TABLE_REF__INIT;
  *message = init_value;
}
size_t table_ref__get_packed_size
                     (const TableRef *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &table_ref__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t table_ref__pack
                     (const TableRef *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &table_ref__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t table_ref__pack_to_buffer
                     (const TableRef *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &table_ref__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TableRef *
       table_ref__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TableRef *)
     protobuf_c_message_unpack (&table_ref__descriptor,
                                allocator, len, data);
}
void   table_ref__free_unpacked
                     (TableRef *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &table_ref__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   var_term_tuple__init
                     (VarTermTuple         *message)
{
  static VarTermTuple init_value = VAR_TERM_TUPLE__INIT;
  *message = init_value;
}
size_t var_term_tuple__get_packed_size
                     (const VarTermTuple *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &var_term_tuple__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t var_term_tuple__pack
                     (const VarTermTuple *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &var_term_tuple__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t var_term_tuple__pack_to_buffer
                     (const VarTermTuple *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &var_term_tuple__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
VarTermTuple *
       var_term_tuple__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (VarTermTuple *)
     protobuf_c_message_unpack (&var_term_tuple__descriptor,
                                allocator, len, data);
}
void   var_term_tuple__free_unpacked
                     (VarTermTuple *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &var_term_tuple__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   term__let__init
                     (Term__Let         *message)
{
  static Term__Let init_value = TERM__LET__INIT;
  *message = init_value;
}
void   term__call__init
                     (Term__Call         *message)
{
  static Term__Call init_value = TERM__CALL__INIT;
  *message = init_value;
}
void   term__if__init
                     (Term__If         *message)
{
  static Term__If init_value = TERM__IF__INIT;
  *message = init_value;
}
void   term__get_by_key__init
                     (Term__GetByKey         *message)
{
  static Term__GetByKey init_value = TERM__GET_BY_KEY__INIT;
  *message = init_value;
}
void   term__table__init
                     (Term__Table         *message)
{
  static Term__Table init_value = TERM__TABLE__INIT;
  *message = init_value;
}
void   term__init
                     (Term         *message)
{
  static Term init_value = TERM__INIT;
  *message = init_value;
}
size_t term__get_packed_size
                     (const Term *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &term__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t term__pack
                     (const Term *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &term__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t term__pack_to_buffer
                     (const Term *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &term__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Term *
       term__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Term *)
     protobuf_c_message_unpack (&term__descriptor,
                                allocator, len, data);
}
void   term__free_unpacked
                     (Term *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &term__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   builtin__filter__init
                     (Builtin__Filter         *message)
{
  static Builtin__Filter init_value = BUILTIN__FILTER__INIT;
  *message = init_value;
}
void   builtin__map__init
                     (Builtin__Map         *message)
{
  static Builtin__Map init_value = BUILTIN__MAP__INIT;
  *message = init_value;
}
void   builtin__concat_map__init
                     (Builtin__ConcatMap         *message)
{
  static Builtin__ConcatMap init_value = BUILTIN__CONCAT_MAP__INIT;
  *message = init_value;
}
void   builtin__order_by__init
                     (Builtin__OrderBy         *message)
{
  static Builtin__OrderBy init_value = BUILTIN__ORDER_BY__INIT;
  *message = init_value;
}
void   builtin__grouped_map_reduce__init
                     (Builtin__GroupedMapReduce         *message)
{
  static Builtin__GroupedMapReduce init_value = BUILTIN__GROUPED_MAP_REDUCE__INIT;
  *message = init_value;
}
void   builtin__range__init
                     (Builtin__Range         *message)
{
  static Builtin__Range init_value = BUILTIN__RANGE__INIT;
  *message = init_value;
}
void   builtin__init
                     (Builtin         *message)
{
  static Builtin init_value = BUILTIN__INIT;
  *message = init_value;
}
size_t builtin__get_packed_size
                     (const Builtin *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &builtin__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t builtin__pack
                     (const Builtin *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &builtin__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t builtin__pack_to_buffer
                     (const Builtin *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &builtin__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Builtin *
       builtin__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Builtin *)
     protobuf_c_message_unpack (&builtin__descriptor,
                                allocator, len, data);
}
void   builtin__free_unpacked
                     (Builtin *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &builtin__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   reduction__init
                     (Reduction         *message)
{
  static Reduction init_value = REDUCTION__INIT;
  *message = init_value;
}
size_t reduction__get_packed_size
                     (const Reduction *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &reduction__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t reduction__pack
                     (const Reduction *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &reduction__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t reduction__pack_to_buffer
                     (const Reduction *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &reduction__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Reduction *
       reduction__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Reduction *)
     protobuf_c_message_unpack (&reduction__descriptor,
                                allocator, len, data);
}
void   reduction__free_unpacked
                     (Reduction *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &reduction__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mapping__init
                     (Mapping         *message)
{
  static Mapping init_value = MAPPING__INIT;
  *message = init_value;
}
size_t mapping__get_packed_size
                     (const Mapping *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mapping__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mapping__pack
                     (const Mapping *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mapping__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mapping__pack_to_buffer
                     (const Mapping *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mapping__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Mapping *
       mapping__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Mapping *)
     protobuf_c_message_unpack (&mapping__descriptor,
                                allocator, len, data);
}
void   mapping__free_unpacked
                     (Mapping *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mapping__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   predicate__init
                     (Predicate         *message)
{
  static Predicate init_value = PREDICATE__INIT;
  *message = init_value;
}
size_t predicate__get_packed_size
                     (const Predicate *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &predicate__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t predicate__pack
                     (const Predicate *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &predicate__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t predicate__pack_to_buffer
                     (const Predicate *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &predicate__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Predicate *
       predicate__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Predicate *)
     protobuf_c_message_unpack (&predicate__descriptor,
                                allocator, len, data);
}
void   predicate__free_unpacked
                     (Predicate *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &predicate__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   read_query__init
                     (ReadQuery         *message)
{
  static ReadQuery init_value = READ_QUERY__INIT;
  *message = init_value;
}
size_t read_query__get_packed_size
                     (const ReadQuery *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &read_query__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t read_query__pack
                     (const ReadQuery *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &read_query__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t read_query__pack_to_buffer
                     (const ReadQuery *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &read_query__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ReadQuery *
       read_query__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ReadQuery *)
     protobuf_c_message_unpack (&read_query__descriptor,
                                allocator, len, data);
}
void   read_query__free_unpacked
                     (ReadQuery *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &read_query__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   write_query__update__init
                     (WriteQuery__Update         *message)
{
  static WriteQuery__Update init_value = WRITE_QUERY__UPDATE__INIT;
  *message = init_value;
}
void   write_query__delete__init
                     (WriteQuery__Delete         *message)
{
  static WriteQuery__Delete init_value = WRITE_QUERY__DELETE__INIT;
  *message = init_value;
}
void   write_query__mutate__init
                     (WriteQuery__Mutate         *message)
{
  static WriteQuery__Mutate init_value = WRITE_QUERY__MUTATE__INIT;
  *message = init_value;
}
void   write_query__insert__init
                     (WriteQuery__Insert         *message)
{
  static WriteQuery__Insert init_value = WRITE_QUERY__INSERT__INIT;
  *message = init_value;
}
void   write_query__for_each__init
                     (WriteQuery__ForEach         *message)
{
  static WriteQuery__ForEach init_value = WRITE_QUERY__FOR_EACH__INIT;
  *message = init_value;
}
void   write_query__point_update__init
                     (WriteQuery__PointUpdate         *message)
{
  static WriteQuery__PointUpdate init_value = WRITE_QUERY__POINT_UPDATE__INIT;
  *message = init_value;
}
void   write_query__point_delete__init
                     (WriteQuery__PointDelete         *message)
{
  static WriteQuery__PointDelete init_value = WRITE_QUERY__POINT_DELETE__INIT;
  *message = init_value;
}
void   write_query__point_mutate__init
                     (WriteQuery__PointMutate         *message)
{
  static WriteQuery__PointMutate init_value = WRITE_QUERY__POINT_MUTATE__INIT;
  *message = init_value;
}
void   write_query__init
                     (WriteQuery         *message)
{
  static WriteQuery init_value = WRITE_QUERY__INIT;
  *message = init_value;
}
size_t write_query__get_packed_size
                     (const WriteQuery *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &write_query__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t write_query__pack
                     (const WriteQuery *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &write_query__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t write_query__pack_to_buffer
                     (const WriteQuery *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &write_query__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
WriteQuery *
       write_query__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (WriteQuery *)
     protobuf_c_message_unpack (&write_query__descriptor,
                                allocator, len, data);
}
void   write_query__free_unpacked
                     (WriteQuery *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &write_query__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   meta_query__create_table__init
                     (MetaQuery__CreateTable         *message)
{
  static MetaQuery__CreateTable init_value = META_QUERY__CREATE_TABLE__INIT;
  *message = init_value;
}
void   meta_query__init
                     (MetaQuery         *message)
{
  static MetaQuery init_value = META_QUERY__INIT;
  *message = init_value;
}
size_t meta_query__get_packed_size
                     (const MetaQuery *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &meta_query__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t meta_query__pack
                     (const MetaQuery *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &meta_query__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t meta_query__pack_to_buffer
                     (const MetaQuery *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &meta_query__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MetaQuery *
       meta_query__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MetaQuery *)
     protobuf_c_message_unpack (&meta_query__descriptor,
                                allocator, len, data);
}
void   meta_query__free_unpacked
                     (MetaQuery *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &meta_query__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   query__init
                     (Query         *message)
{
  static Query init_value = QUERY__INIT;
  *message = init_value;
}
size_t query__get_packed_size
                     (const Query *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &query__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t query__pack
                     (const Query *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &query__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t query__pack_to_buffer
                     (const Query *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &query__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Query *
       query__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Query *)
     protobuf_c_message_unpack (&query__descriptor,
                                allocator, len, data);
}
void   query__free_unpacked
                     (Query *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &query__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   response__backtrace__init
                     (Response__Backtrace         *message)
{
  static Response__Backtrace init_value = RESPONSE__BACKTRACE__INIT;
  *message = init_value;
}
void   response__init
                     (Response         *message)
{
  static Response init_value = RESPONSE__INIT;
  *message = init_value;
}
size_t response__get_packed_size
                     (const Response *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t response__pack
                     (const Response *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t response__pack_to_buffer
                     (const Response *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Response *
       response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Response *)
     protobuf_c_message_unpack (&response__descriptor,
                                allocator, len, data);
}
void   response__free_unpacked
                     (Response *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const protobuf_c_boolean table_ref__use_outdated__default_value = 0;
static const ProtobufCFieldDescriptor table_ref__field_descriptors[3] =
{
  {
    "db_name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TableRef, db_name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "table_name",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TableRef, table_name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "use_outdated",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(TableRef, has_use_outdated),
    PROTOBUF_C_OFFSETOF(TableRef, use_outdated),
    NULL,
    &table_ref__use_outdated__default_value,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned table_ref__field_indices_by_name[] = {
  0,   /* field[0] = db_name */
  1,   /* field[1] = table_name */
  2,   /* field[2] = use_outdated */
};
static const ProtobufCIntRange table_ref__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor table_ref__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "TableRef",
  "TableRef",
  "TableRef",
  "",
  sizeof(TableRef),
  3,
  table_ref__field_descriptors,
  table_ref__field_indices_by_name,
  1,  table_ref__number_ranges,
  (ProtobufCMessageInit) table_ref__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor var_term_tuple__field_descriptors[2] =
{
  {
    "var",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(VarTermTuple, var),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "term",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(VarTermTuple, term),
    &term__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned var_term_tuple__field_indices_by_name[] = {
  1,   /* field[1] = term */
  0,   /* field[0] = var */
};
static const ProtobufCIntRange var_term_tuple__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor var_term_tuple__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "VarTermTuple",
  "VarTermTuple",
  "VarTermTuple",
  "",
  sizeof(VarTermTuple),
  2,
  var_term_tuple__field_descriptors,
  var_term_tuple__field_indices_by_name,
  1,  var_term_tuple__number_ranges,
  (ProtobufCMessageInit) var_term_tuple__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor term__let__field_descriptors[2] =
{
  {
    "binds",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Term__Let, n_binds),
    PROTOBUF_C_OFFSETOF(Term__Let, binds),
    &var_term_tuple__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "expr",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Term__Let, expr),
    &term__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned term__let__field_indices_by_name[] = {
  0,   /* field[0] = binds */
  1,   /* field[1] = expr */
};
static const ProtobufCIntRange term__let__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor term__let__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Term.Let",
  "Let",
  "Term__Let",
  "",
  sizeof(Term__Let),
  2,
  term__let__field_descriptors,
  term__let__field_indices_by_name,
  1,  term__let__number_ranges,
  (ProtobufCMessageInit) term__let__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor term__call__field_descriptors[2] =
{
  {
    "builtin",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Term__Call, builtin),
    &builtin__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "args",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Term__Call, n_args),
    PROTOBUF_C_OFFSETOF(Term__Call, args),
    &term__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned term__call__field_indices_by_name[] = {
  1,   /* field[1] = args */
  0,   /* field[0] = builtin */
};
static const ProtobufCIntRange term__call__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor term__call__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Term.Call",
  "Call",
  "Term__Call",
  "",
  sizeof(Term__Call),
  2,
  term__call__field_descriptors,
  term__call__field_indices_by_name,
  1,  term__call__number_ranges,
  (ProtobufCMessageInit) term__call__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor term__if__field_descriptors[3] =
{
  {
    "test",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Term__If, test),
    &term__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "true_branch",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Term__If, true_branch),
    &term__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "false_branch",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Term__If, false_branch),
    &term__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned term__if__field_indices_by_name[] = {
  2,   /* field[2] = false_branch */
  0,   /* field[0] = test */
  1,   /* field[1] = true_branch */
};
static const ProtobufCIntRange term__if__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor term__if__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Term.If",
  "If",
  "Term__If",
  "",
  sizeof(Term__If),
  3,
  term__if__field_descriptors,
  term__if__field_indices_by_name,
  1,  term__if__number_ranges,
  (ProtobufCMessageInit) term__if__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor term__get_by_key__field_descriptors[3] =
{
  {
    "table_ref",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Term__GetByKey, table_ref),
    &table_ref__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attrname",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Term__GetByKey, attrname),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Term__GetByKey, key),
    &term__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned term__get_by_key__field_indices_by_name[] = {
  1,   /* field[1] = attrname */
  2,   /* field[2] = key */
  0,   /* field[0] = table_ref */
};
static const ProtobufCIntRange term__get_by_key__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor term__get_by_key__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Term.GetByKey",
  "GetByKey",
  "Term__GetByKey",
  "",
  sizeof(Term__GetByKey),
  3,
  term__get_by_key__field_descriptors,
  term__get_by_key__field_indices_by_name,
  1,  term__get_by_key__number_ranges,
  (ProtobufCMessageInit) term__get_by_key__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor term__table__field_descriptors[1] =
{
  {
    "table_ref",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Term__Table, table_ref),
    &table_ref__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned term__table__field_indices_by_name[] = {
  0,   /* field[0] = table_ref */
};
static const ProtobufCIntRange term__table__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor term__table__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Term.Table",
  "Table",
  "Term__Table",
  "",
  sizeof(Term__Table),
  1,
  term__table__field_descriptors,
  term__table__field_indices_by_name,
  1,  term__table__number_ranges,
  (ProtobufCMessageInit) term__table__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue term__term_type__enum_values_by_number[16] =
{
  { "JSON_NULL", "TERM__TERM_TYPE__JSON_NULL", 0 },
  { "VAR", "TERM__TERM_TYPE__VAR", 1 },
  { "LET", "TERM__TERM_TYPE__LET", 2 },
  { "CALL", "TERM__TERM_TYPE__CALL", 3 },
  { "IF", "TERM__TERM_TYPE__IF", 4 },
  { "ERROR", "TERM__TERM_TYPE__ERROR", 5 },
  { "NUMBER", "TERM__TERM_TYPE__NUMBER", 6 },
  { "STRING", "TERM__TERM_TYPE__STRING", 7 },
  { "JSON", "TERM__TERM_TYPE__JSON", 8 },
  { "BOOL", "TERM__TERM_TYPE__BOOL", 9 },
  { "ARRAY", "TERM__TERM_TYPE__ARRAY", 10 },
  { "OBJECT", "TERM__TERM_TYPE__OBJECT", 11 },
  { "GETBYKEY", "TERM__TERM_TYPE__GETBYKEY", 12 },
  { "TABLE", "TERM__TERM_TYPE__TABLE", 13 },
  { "JAVASCRIPT", "TERM__TERM_TYPE__JAVASCRIPT", 14 },
  { "IMPLICIT_VAR", "TERM__TERM_TYPE__IMPLICIT_VAR", 15 },
};
static const ProtobufCIntRange term__term_type__value_ranges[] = {
{0, 0},{0, 16}
};
const ProtobufCEnumValueIndex term__term_type__enum_values_by_name[16] =
{
  { "ARRAY", 10 },
  { "BOOL", 9 },
  { "CALL", 3 },
  { "ERROR", 5 },
  { "GETBYKEY", 12 },
  { "IF", 4 },
  { "IMPLICIT_VAR", 15 },
  { "JAVASCRIPT", 14 },
  { "JSON", 8 },
  { "JSON_NULL", 0 },
  { "LET", 2 },
  { "NUMBER", 6 },
  { "OBJECT", 11 },
  { "STRING", 7 },
  { "TABLE", 13 },
  { "VAR", 1 },
};
const ProtobufCEnumDescriptor term__term_type__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "Term.TermType",
  "TermType",
  "Term__TermType",
  "",
  16,
  term__term_type__enum_values_by_number,
  16,
  term__term_type__enum_values_by_name,
  1,
  term__term_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor term__field_descriptors[15] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Term, type),
    &term__term_type__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "var",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Term, var),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "let",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Term, let),
    &term__let__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "call",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Term, call),
    &term__call__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "if_",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Term, if_),
    &term__if__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Term, error),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "number",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    PROTOBUF_C_OFFSETOF(Term, has_number),
    PROTOBUF_C_OFFSETOF(Term, number),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "valuestring",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Term, valuestring),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "jsonstring",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Term, jsonstring),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "valuebool",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(Term, has_valuebool),
    PROTOBUF_C_OFFSETOF(Term, valuebool),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "array",
    11,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Term, n_array),
    PROTOBUF_C_OFFSETOF(Term, array),
    &term__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "object",
    12,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Term, n_object),
    PROTOBUF_C_OFFSETOF(Term, object),
    &var_term_tuple__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "get_by_key",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Term, get_by_key),
    &term__get_by_key__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "table",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Term, table),
    &term__table__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "javascript",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Term, javascript),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned term__field_indices_by_name[] = {
  10,   /* field[10] = array */
  3,   /* field[3] = call */
  5,   /* field[5] = error */
  12,   /* field[12] = get_by_key */
  4,   /* field[4] = if_ */
  14,   /* field[14] = javascript */
  8,   /* field[8] = jsonstring */
  2,   /* field[2] = let */
  6,   /* field[6] = number */
  11,   /* field[11] = object */
  13,   /* field[13] = table */
  0,   /* field[0] = type */
  9,   /* field[9] = valuebool */
  7,   /* field[7] = valuestring */
  1,   /* field[1] = var */
};
static const ProtobufCIntRange term__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 14, 12 },
  { 0, 15 }
};
const ProtobufCMessageDescriptor term__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Term",
  "Term",
  "Term",
  "",
  sizeof(Term),
  15,
  term__field_descriptors,
  term__field_indices_by_name,
  2,  term__number_ranges,
  (ProtobufCMessageInit) term__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor builtin__filter__field_descriptors[1] =
{
  {
    "predicate",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Builtin__Filter, predicate),
    &predicate__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned builtin__filter__field_indices_by_name[] = {
  0,   /* field[0] = predicate */
};
static const ProtobufCIntRange builtin__filter__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor builtin__filter__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Builtin.Filter",
  "Filter",
  "Builtin__Filter",
  "",
  sizeof(Builtin__Filter),
  1,
  builtin__filter__field_descriptors,
  builtin__filter__field_indices_by_name,
  1,  builtin__filter__number_ranges,
  (ProtobufCMessageInit) builtin__filter__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor builtin__map__field_descriptors[1] =
{
  {
    "mapping",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Builtin__Map, mapping),
    &mapping__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned builtin__map__field_indices_by_name[] = {
  0,   /* field[0] = mapping */
};
static const ProtobufCIntRange builtin__map__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor builtin__map__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Builtin.Map",
  "Map",
  "Builtin__Map",
  "",
  sizeof(Builtin__Map),
  1,
  builtin__map__field_descriptors,
  builtin__map__field_indices_by_name,
  1,  builtin__map__number_ranges,
  (ProtobufCMessageInit) builtin__map__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor builtin__concat_map__field_descriptors[1] =
{
  {
    "mapping",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Builtin__ConcatMap, mapping),
    &mapping__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned builtin__concat_map__field_indices_by_name[] = {
  0,   /* field[0] = mapping */
};
static const ProtobufCIntRange builtin__concat_map__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor builtin__concat_map__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Builtin.ConcatMap",
  "ConcatMap",
  "Builtin__ConcatMap",
  "",
  sizeof(Builtin__ConcatMap),
  1,
  builtin__concat_map__field_descriptors,
  builtin__concat_map__field_indices_by_name,
  1,  builtin__concat_map__number_ranges,
  (ProtobufCMessageInit) builtin__concat_map__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const protobuf_c_boolean builtin__order_by__ascending__default_value = 1;
static const ProtobufCFieldDescriptor builtin__order_by__field_descriptors[2] =
{
  {
    "attr",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Builtin__OrderBy, attr),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ascending",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(Builtin__OrderBy, has_ascending),
    PROTOBUF_C_OFFSETOF(Builtin__OrderBy, ascending),
    NULL,
    &builtin__order_by__ascending__default_value,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned builtin__order_by__field_indices_by_name[] = {
  1,   /* field[1] = ascending */
  0,   /* field[0] = attr */
};
static const ProtobufCIntRange builtin__order_by__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor builtin__order_by__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Builtin.OrderBy",
  "OrderBy",
  "Builtin__OrderBy",
  "",
  sizeof(Builtin__OrderBy),
  2,
  builtin__order_by__field_descriptors,
  builtin__order_by__field_indices_by_name,
  1,  builtin__order_by__number_ranges,
  (ProtobufCMessageInit) builtin__order_by__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor builtin__grouped_map_reduce__field_descriptors[3] =
{
  {
    "group_mapping",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Builtin__GroupedMapReduce, group_mapping),
    &mapping__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value_mapping",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Builtin__GroupedMapReduce, value_mapping),
    &mapping__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reduction",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Builtin__GroupedMapReduce, reduction),
    &reduction__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned builtin__grouped_map_reduce__field_indices_by_name[] = {
  0,   /* field[0] = group_mapping */
  2,   /* field[2] = reduction */
  1,   /* field[1] = value_mapping */
};
static const ProtobufCIntRange builtin__grouped_map_reduce__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor builtin__grouped_map_reduce__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Builtin.GroupedMapReduce",
  "GroupedMapReduce",
  "Builtin__GroupedMapReduce",
  "",
  sizeof(Builtin__GroupedMapReduce),
  3,
  builtin__grouped_map_reduce__field_descriptors,
  builtin__grouped_map_reduce__field_indices_by_name,
  1,  builtin__grouped_map_reduce__number_ranges,
  (ProtobufCMessageInit) builtin__grouped_map_reduce__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor builtin__range__field_descriptors[3] =
{
  {
    "attrname",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Builtin__Range, attrname),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lowerbound",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Builtin__Range, lowerbound),
    &term__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "upperbound",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Builtin__Range, upperbound),
    &term__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned builtin__range__field_indices_by_name[] = {
  0,   /* field[0] = attrname */
  1,   /* field[1] = lowerbound */
  2,   /* field[2] = upperbound */
};
static const ProtobufCIntRange builtin__range__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor builtin__range__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Builtin.Range",
  "Range",
  "Builtin__Range",
  "",
  sizeof(Builtin__Range),
  3,
  builtin__range__field_descriptors,
  builtin__range__field_indices_by_name,
  1,  builtin__range__number_ranges,
  (ProtobufCMessageInit) builtin__range__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue builtin__builtin_type__enum_values_by_number[33] =
{
  { "NOT", "BUILTIN__BUILTIN_TYPE__NOT", 1 },
  { "GETATTR", "BUILTIN__BUILTIN_TYPE__GETATTR", 2 },
  { "IMPLICIT_GETATTR", "BUILTIN__BUILTIN_TYPE__IMPLICIT_GETATTR", 3 },
  { "HASATTR", "BUILTIN__BUILTIN_TYPE__HASATTR", 4 },
  { "IMPLICIT_HASATTR", "BUILTIN__BUILTIN_TYPE__IMPLICIT_HASATTR", 5 },
  { "PICKATTRS", "BUILTIN__BUILTIN_TYPE__PICKATTRS", 6 },
  { "IMPLICIT_PICKATTRS", "BUILTIN__BUILTIN_TYPE__IMPLICIT_PICKATTRS", 7 },
  { "MAPMERGE", "BUILTIN__BUILTIN_TYPE__MAPMERGE", 8 },
  { "ARRAYAPPEND", "BUILTIN__BUILTIN_TYPE__ARRAYAPPEND", 9 },
  { "SLICE", "BUILTIN__BUILTIN_TYPE__SLICE", 11 },
  { "ADD", "BUILTIN__BUILTIN_TYPE__ADD", 14 },
  { "SUBTRACT", "BUILTIN__BUILTIN_TYPE__SUBTRACT", 15 },
  { "MULTIPLY", "BUILTIN__BUILTIN_TYPE__MULTIPLY", 16 },
  { "DIVIDE", "BUILTIN__BUILTIN_TYPE__DIVIDE", 17 },
  { "MODULO", "BUILTIN__BUILTIN_TYPE__MODULO", 18 },
  { "COMPARE", "BUILTIN__BUILTIN_TYPE__COMPARE", 19 },
  { "FILTER", "BUILTIN__BUILTIN_TYPE__FILTER", 20 },
  { "MAP", "BUILTIN__BUILTIN_TYPE__MAP", 21 },
  { "CONCATMAP", "BUILTIN__BUILTIN_TYPE__CONCATMAP", 22 },
  { "ORDERBY", "BUILTIN__BUILTIN_TYPE__ORDERBY", 23 },
  { "DISTINCT", "BUILTIN__BUILTIN_TYPE__DISTINCT", 24 },
  { "LENGTH", "BUILTIN__BUILTIN_TYPE__LENGTH", 26 },
  { "UNION", "BUILTIN__BUILTIN_TYPE__UNION", 27 },
  { "NTH", "BUILTIN__BUILTIN_TYPE__NTH", 28 },
  { "STREAMTOARRAY", "BUILTIN__BUILTIN_TYPE__STREAMTOARRAY", 29 },
  { "ARRAYTOSTREAM", "BUILTIN__BUILTIN_TYPE__ARRAYTOSTREAM", 30 },
  { "REDUCE", "BUILTIN__BUILTIN_TYPE__REDUCE", 31 },
  { "GROUPEDMAPREDUCE", "BUILTIN__BUILTIN_TYPE__GROUPEDMAPREDUCE", 32 },
  { "ANY", "BUILTIN__BUILTIN_TYPE__ANY", 35 },
  { "ALL", "BUILTIN__BUILTIN_TYPE__ALL", 36 },
  { "RANGE", "BUILTIN__BUILTIN_TYPE__RANGE", 37 },
  { "IMPLICIT_WITHOUT", "BUILTIN__BUILTIN_TYPE__IMPLICIT_WITHOUT", 38 },
  { "WITHOUT", "BUILTIN__BUILTIN_TYPE__WITHOUT", 39 },
};
static const ProtobufCIntRange builtin__builtin_type__value_ranges[] = {
{1, 0},{11, 9},{14, 10},{26, 21},{35, 28},{0, 33}
};
const ProtobufCEnumValueIndex builtin__builtin_type__enum_values_by_name[33] =
{
  { "ADD", 10 },
  { "ALL", 29 },
  { "ANY", 28 },
  { "ARRAYAPPEND", 8 },
  { "ARRAYTOSTREAM", 25 },
  { "COMPARE", 15 },
  { "CONCATMAP", 18 },
  { "DISTINCT", 20 },
  { "DIVIDE", 13 },
  { "FILTER", 16 },
  { "GETATTR", 1 },
  { "GROUPEDMAPREDUCE", 27 },
  { "HASATTR", 3 },
  { "IMPLICIT_GETATTR", 2 },
  { "IMPLICIT_HASATTR", 4 },
  { "IMPLICIT_PICKATTRS", 6 },
  { "IMPLICIT_WITHOUT", 31 },
  { "LENGTH", 21 },
  { "MAP", 17 },
  { "MAPMERGE", 7 },
  { "MODULO", 14 },
  { "MULTIPLY", 12 },
  { "NOT", 0 },
  { "NTH", 23 },
  { "ORDERBY", 19 },
  { "PICKATTRS", 5 },
  { "RANGE", 30 },
  { "REDUCE", 26 },
  { "SLICE", 9 },
  { "STREAMTOARRAY", 24 },
  { "SUBTRACT", 11 },
  { "UNION", 22 },
  { "WITHOUT", 32 },
};
const ProtobufCEnumDescriptor builtin__builtin_type__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "Builtin.BuiltinType",
  "BuiltinType",
  "Builtin__BuiltinType",
  "",
  33,
  builtin__builtin_type__enum_values_by_number,
  33,
  builtin__builtin_type__enum_values_by_name,
  5,
  builtin__builtin_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
const ProtobufCEnumValue builtin__comparison__enum_values_by_number[6] =
{
  { "EQ", "BUILTIN__COMPARISON__EQ", 1 },
  { "NE", "BUILTIN__COMPARISON__NE", 2 },
  { "LT", "BUILTIN__COMPARISON__LT", 3 },
  { "LE", "BUILTIN__COMPARISON__LE", 4 },
  { "GT", "BUILTIN__COMPARISON__GT", 5 },
  { "GE", "BUILTIN__COMPARISON__GE", 6 },
};
static const ProtobufCIntRange builtin__comparison__value_ranges[] = {
{1, 0},{0, 6}
};
const ProtobufCEnumValueIndex builtin__comparison__enum_values_by_name[6] =
{
  { "EQ", 0 },
  { "GE", 5 },
  { "GT", 4 },
  { "LE", 3 },
  { "LT", 2 },
  { "NE", 1 },
};
const ProtobufCEnumDescriptor builtin__comparison__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "Builtin.Comparison",
  "Comparison",
  "Builtin__Comparison",
  "",
  6,
  builtin__comparison__enum_values_by_number,
  6,
  builtin__comparison__enum_values_by_name,
  1,
  builtin__comparison__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor builtin__field_descriptors[11] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Builtin, type),
    &builtin__builtin_type__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attr",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Builtin, attr),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attrs",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    PROTOBUF_C_OFFSETOF(Builtin, n_attrs),
    PROTOBUF_C_OFFSETOF(Builtin, attrs),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "comparison",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    PROTOBUF_C_OFFSETOF(Builtin, has_comparison),
    PROTOBUF_C_OFFSETOF(Builtin, comparison),
    &builtin__comparison__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "filter",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Builtin, filter),
    &builtin__filter__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "map",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Builtin, map),
    &builtin__map__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "concat_map",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Builtin, concat_map),
    &builtin__concat_map__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "order_by",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Builtin, n_order_by),
    PROTOBUF_C_OFFSETOF(Builtin, order_by),
    &builtin__order_by__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reduce",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Builtin, reduce),
    &reduction__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "grouped_map_reduce",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Builtin, grouped_map_reduce),
    &builtin__grouped_map_reduce__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "range",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Builtin, range),
    &builtin__range__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned builtin__field_indices_by_name[] = {
  1,   /* field[1] = attr */
  2,   /* field[2] = attrs */
  3,   /* field[3] = comparison */
  6,   /* field[6] = concat_map */
  4,   /* field[4] = filter */
  9,   /* field[9] = grouped_map_reduce */
  5,   /* field[5] = map */
  7,   /* field[7] = order_by */
  10,   /* field[10] = range */
  8,   /* field[8] = reduce */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange builtin__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor builtin__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Builtin",
  "Builtin",
  "Builtin",
  "",
  sizeof(Builtin),
  11,
  builtin__field_descriptors,
  builtin__field_indices_by_name,
  1,  builtin__number_ranges,
  (ProtobufCMessageInit) builtin__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor reduction__field_descriptors[4] =
{
  {
    "base",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Reduction, base),
    &term__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "var1",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Reduction, var1),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "var2",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Reduction, var2),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "body",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Reduction, body),
    &term__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned reduction__field_indices_by_name[] = {
  0,   /* field[0] = base */
  3,   /* field[3] = body */
  1,   /* field[1] = var1 */
  2,   /* field[2] = var2 */
};
static const ProtobufCIntRange reduction__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor reduction__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Reduction",
  "Reduction",
  "Reduction",
  "",
  sizeof(Reduction),
  4,
  reduction__field_descriptors,
  reduction__field_indices_by_name,
  1,  reduction__number_ranges,
  (ProtobufCMessageInit) reduction__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mapping__field_descriptors[2] =
{
  {
    "arg",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Mapping, arg),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "body",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Mapping, body),
    &term__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mapping__field_indices_by_name[] = {
  0,   /* field[0] = arg */
  1,   /* field[1] = body */
};
static const ProtobufCIntRange mapping__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor mapping__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Mapping",
  "Mapping",
  "Mapping",
  "",
  sizeof(Mapping),
  2,
  mapping__field_descriptors,
  mapping__field_indices_by_name,
  1,  mapping__number_ranges,
  (ProtobufCMessageInit) mapping__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor predicate__field_descriptors[2] =
{
  {
    "arg",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Predicate, arg),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "body",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Predicate, body),
    &term__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned predicate__field_indices_by_name[] = {
  0,   /* field[0] = arg */
  1,   /* field[1] = body */
};
static const ProtobufCIntRange predicate__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor predicate__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Predicate",
  "Predicate",
  "Predicate",
  "",
  sizeof(Predicate),
  2,
  predicate__field_descriptors,
  predicate__field_indices_by_name,
  1,  predicate__number_ranges,
  (ProtobufCMessageInit) predicate__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor read_query__field_descriptors[3] =
{
  {
    "term",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ReadQuery, term),
    &term__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_chunk_size",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    PROTOBUF_C_OFFSETOF(ReadQuery, has_max_chunk_size),
    PROTOBUF_C_OFFSETOF(ReadQuery, max_chunk_size),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_age",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    PROTOBUF_C_OFFSETOF(ReadQuery, has_max_age),
    PROTOBUF_C_OFFSETOF(ReadQuery, max_age),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned read_query__field_indices_by_name[] = {
  2,   /* field[2] = max_age */
  1,   /* field[1] = max_chunk_size */
  0,   /* field[0] = term */
};
static const ProtobufCIntRange read_query__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor read_query__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ReadQuery",
  "ReadQuery",
  "ReadQuery",
  "",
  sizeof(ReadQuery),
  3,
  read_query__field_descriptors,
  read_query__field_indices_by_name,
  1,  read_query__number_ranges,
  (ProtobufCMessageInit) read_query__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor write_query__update__field_descriptors[2] =
{
  {
    "view",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(WriteQuery__Update, view),
    &term__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mapping",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(WriteQuery__Update, mapping),
    &mapping__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned write_query__update__field_indices_by_name[] = {
  1,   /* field[1] = mapping */
  0,   /* field[0] = view */
};
static const ProtobufCIntRange write_query__update__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor write_query__update__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "WriteQuery.Update",
  "Update",
  "WriteQuery__Update",
  "",
  sizeof(WriteQuery__Update),
  2,
  write_query__update__field_descriptors,
  write_query__update__field_indices_by_name,
  1,  write_query__update__number_ranges,
  (ProtobufCMessageInit) write_query__update__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor write_query__delete__field_descriptors[1] =
{
  {
    "view",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(WriteQuery__Delete, view),
    &term__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned write_query__delete__field_indices_by_name[] = {
  0,   /* field[0] = view */
};
static const ProtobufCIntRange write_query__delete__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor write_query__delete__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "WriteQuery.Delete",
  "Delete",
  "WriteQuery__Delete",
  "",
  sizeof(WriteQuery__Delete),
  1,
  write_query__delete__field_descriptors,
  write_query__delete__field_indices_by_name,
  1,  write_query__delete__number_ranges,
  (ProtobufCMessageInit) write_query__delete__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor write_query__mutate__field_descriptors[2] =
{
  {
    "view",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(WriteQuery__Mutate, view),
    &term__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mapping",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(WriteQuery__Mutate, mapping),
    &mapping__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned write_query__mutate__field_indices_by_name[] = {
  1,   /* field[1] = mapping */
  0,   /* field[0] = view */
};
static const ProtobufCIntRange write_query__mutate__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor write_query__mutate__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "WriteQuery.Mutate",
  "Mutate",
  "WriteQuery__Mutate",
  "",
  sizeof(WriteQuery__Mutate),
  2,
  write_query__mutate__field_descriptors,
  write_query__mutate__field_indices_by_name,
  1,  write_query__mutate__number_ranges,
  (ProtobufCMessageInit) write_query__mutate__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const protobuf_c_boolean write_query__insert__overwrite__default_value = 0;
static const ProtobufCFieldDescriptor write_query__insert__field_descriptors[3] =
{
  {
    "table_ref",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(WriteQuery__Insert, table_ref),
    &table_ref__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "terms",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(WriteQuery__Insert, n_terms),
    PROTOBUF_C_OFFSETOF(WriteQuery__Insert, terms),
    &term__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "overwrite",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(WriteQuery__Insert, has_overwrite),
    PROTOBUF_C_OFFSETOF(WriteQuery__Insert, overwrite),
    NULL,
    &write_query__insert__overwrite__default_value,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned write_query__insert__field_indices_by_name[] = {
  2,   /* field[2] = overwrite */
  0,   /* field[0] = table_ref */
  1,   /* field[1] = terms */
};
static const ProtobufCIntRange write_query__insert__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor write_query__insert__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "WriteQuery.Insert",
  "Insert",
  "WriteQuery__Insert",
  "",
  sizeof(WriteQuery__Insert),
  3,
  write_query__insert__field_descriptors,
  write_query__insert__field_indices_by_name,
  1,  write_query__insert__number_ranges,
  (ProtobufCMessageInit) write_query__insert__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor write_query__for_each__field_descriptors[3] =
{
  {
    "stream",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(WriteQuery__ForEach, stream),
    &term__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "var",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(WriteQuery__ForEach, var),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "queries",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(WriteQuery__ForEach, n_queries),
    PROTOBUF_C_OFFSETOF(WriteQuery__ForEach, queries),
    &write_query__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned write_query__for_each__field_indices_by_name[] = {
  2,   /* field[2] = queries */
  0,   /* field[0] = stream */
  1,   /* field[1] = var */
};
static const ProtobufCIntRange write_query__for_each__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor write_query__for_each__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "WriteQuery.ForEach",
  "ForEach",
  "WriteQuery__ForEach",
  "",
  sizeof(WriteQuery__ForEach),
  3,
  write_query__for_each__field_descriptors,
  write_query__for_each__field_indices_by_name,
  1,  write_query__for_each__number_ranges,
  (ProtobufCMessageInit) write_query__for_each__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor write_query__point_update__field_descriptors[4] =
{
  {
    "table_ref",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(WriteQuery__PointUpdate, table_ref),
    &table_ref__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attrname",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(WriteQuery__PointUpdate, attrname),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(WriteQuery__PointUpdate, key),
    &term__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mapping",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(WriteQuery__PointUpdate, mapping),
    &mapping__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned write_query__point_update__field_indices_by_name[] = {
  1,   /* field[1] = attrname */
  2,   /* field[2] = key */
  3,   /* field[3] = mapping */
  0,   /* field[0] = table_ref */
};
static const ProtobufCIntRange write_query__point_update__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor write_query__point_update__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "WriteQuery.PointUpdate",
  "PointUpdate",
  "WriteQuery__PointUpdate",
  "",
  sizeof(WriteQuery__PointUpdate),
  4,
  write_query__point_update__field_descriptors,
  write_query__point_update__field_indices_by_name,
  1,  write_query__point_update__number_ranges,
  (ProtobufCMessageInit) write_query__point_update__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor write_query__point_delete__field_descriptors[3] =
{
  {
    "table_ref",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(WriteQuery__PointDelete, table_ref),
    &table_ref__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attrname",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(WriteQuery__PointDelete, attrname),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(WriteQuery__PointDelete, key),
    &term__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned write_query__point_delete__field_indices_by_name[] = {
  1,   /* field[1] = attrname */
  2,   /* field[2] = key */
  0,   /* field[0] = table_ref */
};
static const ProtobufCIntRange write_query__point_delete__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor write_query__point_delete__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "WriteQuery.PointDelete",
  "PointDelete",
  "WriteQuery__PointDelete",
  "",
  sizeof(WriteQuery__PointDelete),
  3,
  write_query__point_delete__field_descriptors,
  write_query__point_delete__field_indices_by_name,
  1,  write_query__point_delete__number_ranges,
  (ProtobufCMessageInit) write_query__point_delete__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor write_query__point_mutate__field_descriptors[4] =
{
  {
    "table_ref",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(WriteQuery__PointMutate, table_ref),
    &table_ref__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attrname",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(WriteQuery__PointMutate, attrname),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(WriteQuery__PointMutate, key),
    &term__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mapping",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(WriteQuery__PointMutate, mapping),
    &mapping__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned write_query__point_mutate__field_indices_by_name[] = {
  1,   /* field[1] = attrname */
  2,   /* field[2] = key */
  3,   /* field[3] = mapping */
  0,   /* field[0] = table_ref */
};
static const ProtobufCIntRange write_query__point_mutate__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor write_query__point_mutate__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "WriteQuery.PointMutate",
  "PointMutate",
  "WriteQuery__PointMutate",
  "",
  sizeof(WriteQuery__PointMutate),
  4,
  write_query__point_mutate__field_descriptors,
  write_query__point_mutate__field_indices_by_name,
  1,  write_query__point_mutate__number_ranges,
  (ProtobufCMessageInit) write_query__point_mutate__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue write_query__write_query_type__enum_values_by_number[8] =
{
  { "UPDATE", "WRITE_QUERY__WRITE_QUERY_TYPE__UPDATE", 1 },
  { "DELETE", "WRITE_QUERY__WRITE_QUERY_TYPE__DELETE", 2 },
  { "MUTATE", "WRITE_QUERY__WRITE_QUERY_TYPE__MUTATE", 3 },
  { "INSERT", "WRITE_QUERY__WRITE_QUERY_TYPE__INSERT", 4 },
  { "FOREACH", "WRITE_QUERY__WRITE_QUERY_TYPE__FOREACH", 6 },
  { "POINTUPDATE", "WRITE_QUERY__WRITE_QUERY_TYPE__POINTUPDATE", 7 },
  { "POINTDELETE", "WRITE_QUERY__WRITE_QUERY_TYPE__POINTDELETE", 8 },
  { "POINTMUTATE", "WRITE_QUERY__WRITE_QUERY_TYPE__POINTMUTATE", 9 },
};
static const ProtobufCIntRange write_query__write_query_type__value_ranges[] = {
{1, 0},{6, 4},{0, 8}
};
const ProtobufCEnumValueIndex write_query__write_query_type__enum_values_by_name[8] =
{
  { "DELETE", 1 },
  { "FOREACH", 4 },
  { "INSERT", 3 },
  { "MUTATE", 2 },
  { "POINTDELETE", 6 },
  { "POINTMUTATE", 7 },
  { "POINTUPDATE", 5 },
  { "UPDATE", 0 },
};
const ProtobufCEnumDescriptor write_query__write_query_type__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "WriteQuery.WriteQueryType",
  "WriteQueryType",
  "WriteQuery__WriteQueryType",
  "",
  8,
  write_query__write_query_type__enum_values_by_number,
  8,
  write_query__write_query_type__enum_values_by_name,
  2,
  write_query__write_query_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const protobuf_c_boolean write_query__atomic__default_value = 1;
static const ProtobufCFieldDescriptor write_query__field_descriptors[10] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(WriteQuery, type),
    &write_query__write_query_type__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "update",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(WriteQuery, update),
    &write_query__update__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "delete",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(WriteQuery, delete_),
    &write_query__delete__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mutate",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(WriteQuery, mutate),
    &write_query__mutate__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "insert",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(WriteQuery, insert),
    &write_query__insert__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "for_each",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(WriteQuery, for_each),
    &write_query__for_each__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "point_update",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(WriteQuery, point_update),
    &write_query__point_update__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "point_delete",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(WriteQuery, point_delete),
    &write_query__point_delete__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "point_mutate",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(WriteQuery, point_mutate),
    &write_query__point_mutate__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "atomic",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(WriteQuery, has_atomic),
    PROTOBUF_C_OFFSETOF(WriteQuery, atomic),
    NULL,
    &write_query__atomic__default_value,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned write_query__field_indices_by_name[] = {
  9,   /* field[9] = atomic */
  2,   /* field[2] = delete */
  5,   /* field[5] = for_each */
  4,   /* field[4] = insert */
  3,   /* field[3] = mutate */
  7,   /* field[7] = point_delete */
  8,   /* field[8] = point_mutate */
  6,   /* field[6] = point_update */
  0,   /* field[0] = type */
  1,   /* field[1] = update */
};
static const ProtobufCIntRange write_query__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 7, 5 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor write_query__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "WriteQuery",
  "WriteQuery",
  "WriteQuery",
  "",
  sizeof(WriteQuery),
  10,
  write_query__field_descriptors,
  write_query__field_indices_by_name,
  2,  write_query__number_ranges,
  (ProtobufCMessageInit) write_query__init,
  NULL,NULL,NULL    /* reserved[123] */
};
char meta_query__create_table__primary_key__default_value[] = "id";
static const int64_t meta_query__create_table__cache_size__default_value = 1073741824;
static const ProtobufCFieldDescriptor meta_query__create_table__field_descriptors[4] =
{
  {
    "datacenter",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(MetaQuery__CreateTable, datacenter),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "table_ref",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(MetaQuery__CreateTable, table_ref),
    &table_ref__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "primary_key",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(MetaQuery__CreateTable, primary_key),
    NULL,
    &meta_query__create_table__primary_key__default_value,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cache_size",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    PROTOBUF_C_OFFSETOF(MetaQuery__CreateTable, has_cache_size),
    PROTOBUF_C_OFFSETOF(MetaQuery__CreateTable, cache_size),
    NULL,
    &meta_query__create_table__cache_size__default_value,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned meta_query__create_table__field_indices_by_name[] = {
  3,   /* field[3] = cache_size */
  0,   /* field[0] = datacenter */
  2,   /* field[2] = primary_key */
  1,   /* field[1] = table_ref */
};
static const ProtobufCIntRange meta_query__create_table__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 3, 1 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor meta_query__create_table__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "MetaQuery.CreateTable",
  "CreateTable",
  "MetaQuery__CreateTable",
  "",
  sizeof(MetaQuery__CreateTable),
  4,
  meta_query__create_table__field_descriptors,
  meta_query__create_table__field_indices_by_name,
  2,  meta_query__create_table__number_ranges,
  (ProtobufCMessageInit) meta_query__create_table__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue meta_query__meta_query_type__enum_values_by_number[6] =
{
  { "CREATE_DB", "META_QUERY__META_QUERY_TYPE__CREATE_DB", 1 },
  { "DROP_DB", "META_QUERY__META_QUERY_TYPE__DROP_DB", 2 },
  { "LIST_DBS", "META_QUERY__META_QUERY_TYPE__LIST_DBS", 3 },
  { "CREATE_TABLE", "META_QUERY__META_QUERY_TYPE__CREATE_TABLE", 4 },
  { "DROP_TABLE", "META_QUERY__META_QUERY_TYPE__DROP_TABLE", 5 },
  { "LIST_TABLES", "META_QUERY__META_QUERY_TYPE__LIST_TABLES", 6 },
};
static const ProtobufCIntRange meta_query__meta_query_type__value_ranges[] = {
{1, 0},{0, 6}
};
const ProtobufCEnumValueIndex meta_query__meta_query_type__enum_values_by_name[6] =
{
  { "CREATE_DB", 0 },
  { "CREATE_TABLE", 3 },
  { "DROP_DB", 1 },
  { "DROP_TABLE", 4 },
  { "LIST_DBS", 2 },
  { "LIST_TABLES", 5 },
};
const ProtobufCEnumDescriptor meta_query__meta_query_type__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "MetaQuery.MetaQueryType",
  "MetaQueryType",
  "MetaQuery__MetaQueryType",
  "",
  6,
  meta_query__meta_query_type__enum_values_by_number,
  6,
  meta_query__meta_query_type__enum_values_by_name,
  1,
  meta_query__meta_query_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor meta_query__field_descriptors[4] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(MetaQuery, type),
    &meta_query__meta_query_type__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "db_name",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(MetaQuery, db_name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "create_table",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(MetaQuery, create_table),
    &meta_query__create_table__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "drop_table",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(MetaQuery, drop_table),
    &table_ref__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned meta_query__field_indices_by_name[] = {
  2,   /* field[2] = create_table */
  1,   /* field[1] = db_name */
  3,   /* field[3] = drop_table */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange meta_query__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor meta_query__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "MetaQuery",
  "MetaQuery",
  "MetaQuery",
  "",
  sizeof(MetaQuery),
  4,
  meta_query__field_descriptors,
  meta_query__field_indices_by_name,
  1,  meta_query__number_ranges,
  (ProtobufCMessageInit) meta_query__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue query__query_type__enum_values_by_number[5] =
{
  { "READ", "QUERY__QUERY_TYPE__READ", 1 },
  { "WRITE", "QUERY__QUERY_TYPE__WRITE", 2 },
  { "CONTINUE", "QUERY__QUERY_TYPE__CONTINUE", 3 },
  { "STOP", "QUERY__QUERY_TYPE__STOP", 4 },
  { "META", "QUERY__QUERY_TYPE__META", 5 },
};
static const ProtobufCIntRange query__query_type__value_ranges[] = {
{1, 0},{0, 5}
};
const ProtobufCEnumValueIndex query__query_type__enum_values_by_name[5] =
{
  { "CONTINUE", 2 },
  { "META", 4 },
  { "READ", 0 },
  { "STOP", 3 },
  { "WRITE", 1 },
};
const ProtobufCEnumDescriptor query__query_type__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "Query.QueryType",
  "QueryType",
  "Query__QueryType",
  "",
  5,
  query__query_type__enum_values_by_number,
  5,
  query__query_type__enum_values_by_name,
  1,
  query__query_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor query__field_descriptors[5] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Query, type),
    &query__query_type__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "token",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Query, token),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "read_query",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Query, read_query),
    &read_query__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "write_query",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Query, write_query),
    &write_query__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "meta_query",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Query, meta_query),
    &meta_query__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned query__field_indices_by_name[] = {
  4,   /* field[4] = meta_query */
  2,   /* field[2] = read_query */
  1,   /* field[1] = token */
  0,   /* field[0] = type */
  3,   /* field[3] = write_query */
};
static const ProtobufCIntRange query__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor query__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Query",
  "Query",
  "Query",
  "",
  sizeof(Query),
  5,
  query__field_descriptors,
  query__field_indices_by_name,
  1,  query__number_ranges,
  (ProtobufCMessageInit) query__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor response__backtrace__field_descriptors[1] =
{
  {
    "frame",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    PROTOBUF_C_OFFSETOF(Response__Backtrace, n_frame),
    PROTOBUF_C_OFFSETOF(Response__Backtrace, frame),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response__backtrace__field_indices_by_name[] = {
  0,   /* field[0] = frame */
};
static const ProtobufCIntRange response__backtrace__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor response__backtrace__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Response.Backtrace",
  "Backtrace",
  "Response__Backtrace",
  "",
  sizeof(Response__Backtrace),
  1,
  response__backtrace__field_descriptors,
  response__backtrace__field_indices_by_name,
  1,  response__backtrace__number_ranges,
  (ProtobufCMessageInit) response__backtrace__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue response__status_code__enum_values_by_number[7] =
{
  { "SUCCESS_EMPTY", "RESPONSE__STATUS_CODE__SUCCESS_EMPTY", 0 },
  { "SUCCESS_JSON", "RESPONSE__STATUS_CODE__SUCCESS_JSON", 1 },
  { "SUCCESS_PARTIAL", "RESPONSE__STATUS_CODE__SUCCESS_PARTIAL", 2 },
  { "SUCCESS_STREAM", "RESPONSE__STATUS_CODE__SUCCESS_STREAM", 3 },
  { "BROKEN_CLIENT", "RESPONSE__STATUS_CODE__BROKEN_CLIENT", 101 },
  { "BAD_QUERY", "RESPONSE__STATUS_CODE__BAD_QUERY", 102 },
  { "RUNTIME_ERROR", "RESPONSE__STATUS_CODE__RUNTIME_ERROR", 103 },
};
static const ProtobufCIntRange response__status_code__value_ranges[] = {
{0, 0},{101, 4},{0, 7}
};
const ProtobufCEnumValueIndex response__status_code__enum_values_by_name[7] =
{
  { "BAD_QUERY", 5 },
  { "BROKEN_CLIENT", 4 },
  { "RUNTIME_ERROR", 6 },
  { "SUCCESS_EMPTY", 0 },
  { "SUCCESS_JSON", 1 },
  { "SUCCESS_PARTIAL", 2 },
  { "SUCCESS_STREAM", 3 },
};
const ProtobufCEnumDescriptor response__status_code__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "Response.StatusCode",
  "StatusCode",
  "Response__StatusCode",
  "",
  7,
  response__status_code__enum_values_by_number,
  7,
  response__status_code__enum_values_by_name,
  2,
  response__status_code__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor response__field_descriptors[5] =
{
  {
    "status_code",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Response, status_code),
    &response__status_code__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "token",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Response, token),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "response",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    PROTOBUF_C_OFFSETOF(Response, n_response),
    PROTOBUF_C_OFFSETOF(Response, response),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error_message",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Response, error_message),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "backtrace",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Response, backtrace),
    &response__backtrace__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response__field_indices_by_name[] = {
  4,   /* field[4] = backtrace */
  3,   /* field[3] = error_message */
  2,   /* field[2] = response */
  0,   /* field[0] = status_code */
  1,   /* field[1] = token */
};
static const ProtobufCIntRange response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor response__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Response",
  "Response",
  "Response",
  "",
  sizeof(Response),
  5,
  response__field_descriptors,
  response__field_indices_by_name,
  1,  response__number_ranges,
  (ProtobufCMessageInit) response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
